In [2]:
import numpy as np
from sklearn.linear_model import SGDClassifier

In [ ]:
### Implementando un AND
Recordemos que la tabla de AND es:

0 AND 0 = 0

0 AND 1 = 0

1 AND 0 = 0

1 AND 1 = 1


### Implementando un OR
Recordemos que la tabla de OR es:

0 OR 0 = 0

0 OR 1 = 1

1 OR 0 = 1

1 OR 1 = 1

### Implementando un NOT
Recordemos que la tabla de NOT es:

NOT 0 = 1
NOT 1 = 0

### Implementando un XOR (y fallando en el proceso)
Recordemos que la tabla de XOR es:

0 XOR 0 = 0

0 XOR 1 = 1

1 XOR 0 = 1

1 XOR 1 = 0

In [3]:
# AND
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,0,0,1])

model = SGDClassifier(max_iter= 1000)
model.fit(X,Y)
RESULTADO = model.predict(X)
print(RESULTADO)

[0 0 0 1]


In [5]:
# OR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,1,1,1])

model = SGDClassifier(max_iter= 1000)
model.fit(X,Y)
RESULTADO = model.predict(X)
print(RESULTADO)

[0 1 1 1]


In [6]:
# not
X = np.array([[0],[1]])
Y = np.array([1,0])

model = SGDClassifier(max_iter= 1000)
model.fit(X,Y)
RESULTADO = model.predict(X)
print(RESULTADO)

[1 0]


In [7]:
# XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,1,1,0])

model = SGDClassifier(max_iter= 1000)
model.fit(X,Y)
RESULTADO = model.predict(X)
print(RESULTADO)

[0 1 0 1]
